--[[
Created by IntelliJ IDEA.
User: WareBare
Date: 1/20/2017
Time: 4:56 PM

fn - functions

global functions/lua hooks called by dbr or conv
files starting with 'g' have been generated by WanezModdingTools

package: fn
]]

wanez.fn = {}

--- DGA
wanez.fn.gDGA = {}
Script.Load("wanez/scripts/fn/gDGA.lua");

--- Runic Inscriptions
wanez.fn.gRunes = {}
Script.Load("wanez/scripts/fn/gRunes.lua");
wanez.fn.gRuneStones = {}
Script.Load("wanez/scripts/fn/gRuneStones.lua");
