--[[
Created by IntelliJ IDEA.
User: WareBare
Date: 1/20/2017
Time: 4:56 PM

data

data arrays
files starting with 'g' have been generated by WanezModdingTools

Package: data
]]--

wanez.data = {}

--- DGA
Script.Load("wanez/scripts/data/gEnemies.lua");
Script.Load("wanez/scripts/data/gNameToId.lua");

--- Runic Inscriptions
Script.Load("wanez/scripts/data/gInscriptions.lua");
